[package]
name = "algo-wasm"
version = "0.1.0"
description = "Algorithm for Substring Tiler, implemented in Rust"
repository = "https://github.com/mbs9/substr"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
lto = true
