name: Docker Image CI

permissions:
  packages: write

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: cd frontend/ && npm install && npm run build
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }} # important!

    - name: Build and push to Github registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/mbs9/substr-analyzer:latest
        file: "Dockerfile"
    - name: Build and push to Github registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/mbs9/substr-analyzer-ui:latest
        file: "Dockerfile.web"
